"use strict";
const tg=window.Telegram?.WebApp, query=new URLSearchParams(location.search), form=document.getElementById('intake');
let lang=query.get('lang')==='uz'?'uz':'ru', reference, point, sending=false;
const mode=['deal','support'].includes(query.get('mode'))?query.get('mode'):'pharmacy';
const texts={
ru:{heading:mode==='deal'?'Создать сделку':mode==='support'?'Заявка в техподдержку':'Добавить аптеку',intro:'Перед сохранением проверим данные в боте.',choosePharmacy:mode==='support'?'🏪 На какую аптеку создать заявку?':'🏪 На какую аптеку создать сделку?',newPharmacy:'Новая — добавить в базу',existingPharmacy:'Уже есть в базе',fomHint:'По FOM ID найдём аптеку и компанию. Заново заполнять их не нужно.',pharmacy:'🏪 Аптека',title:'Название аптеки *',region:'Бизнес-регион *',city:'Город / район *',address:'Адрес: улица и дом *',program:'Текущая программа *',location:'📍 Добавить мою геопозицию',locationHint:'Необязательно. Нажимайте, если вы сейчас в этой аптеке.',remove:'Убрать',company:'🏢 Компания / Фирма',inn:'ИНН *',companyName:'Наименование (ООО, ИП, СП, ЯТТ)',companyHint:'По ИНН найдём компанию. Если её нет, создадим с этим названием.',contact:'👤 Контакт',phone:'Телефон',phoneHint:'Можно без +998. Можно оставить пустым.',createContact:'Создать этого человека на вас в Б24?',contactHint:'Без галочки номер сохраним только у аптеки, без имени человека. Если контакт уже есть, используем его.',name:'Имя контакта',nameHint:'Фамилия необязательна. Для существующего контакта можно оставить пустым.',position:'Должность',reminder:'🔔 Напоминание в сделке',addReminder:'Добавить вам напоминание о работе с клиентом?',action:'Что нужно сделать с клиентом?',actionHint:'Напишите для себя коротко, чтобы бот напомнил вам в Telegram.',deadline:'Когда? Время Ташкента',chooseDate:'📅 Выбрать дату и время',timezone:'🕒 Время Ташкента',today:'Сегодня',tomorrow:'Завтра',hour:'Время',apply:'Выбрать',support:'🛠 Заявка в техподдержку',requestTitle:'Тема заявки *',requestDescription:'Что случилось и какая помощь нужна? *',recipientHint:'Оставить в очереди или назначить технику? В боте выберете маршрут, регион и техника. Есть поиск по имени и фамилии.',reviewHint:'Кнопка отправит черновик в бот. В Б24 сохраним после вашего подтверждения.',submit:'Проверить в боте →',select:'Выберите',loadError:'Не удалось открыть справочники. Закройте форму и попробуйте ещё раз.',geoError:'Геопозиция не получена. Разрешите доступ или пропустите этот шаг.',openBot:'Откройте форму кнопкой в Telegram-боте. Из обычного браузера данные не отправляются.',sizeError:'Слишком много текста. Сократите описание, названия или адрес.',dateError:'Выберите будущую дату и время напоминания.',sending:'⏳ Отправляем в бот…'},
uz:{heading:mode==='deal'?'Сделка очиш':mode==='support'?'Техник ёрдам заявкаси':'Дорихона қўшиш',intro:'Сақлашдан олдин ботда маълумотларни текширамиз.',choosePharmacy:mode==='support'?'🏪 Қайси дорихонага заявка яратамиз?':'🏪 Қайси дорихонага сделка яратамиз?',newPharmacy:'Янги — базага қўшиш',existingPharmacy:'Базада бор',fomHint:'FOM ID бўйича дорихона ва компанияни топамиз. Қайта тўлдириш шарт эмас.',pharmacy:'🏪 Дорихона',title:'Дорихона номи *',region:'Бизнес-ҳудуд *',city:'Шаҳар / туман *',address:'Манзил: кўча ва уй *',program:'Ҳозир ишлатилаётган дастур *',location:'📍 Геопозициямни қўшиш',locationHint:'Мажбурий эмас. Ҳозир шу дорихонада бўлсангиз, босинг.',remove:'Ўчириш',company:'🏢 Компания / Фирма',inn:'ИНН *',companyName:'Номи (ООО, ИП, СП, ЯТТ)',companyHint:'Компанияни ИНН бўйича топамиз. Топилмаса, шу ном билан яратамиз.',contact:'👤 Контакт',phone:'Телефон',phoneHint:'+998сиз мумкин. Бўш қолдириш ҳам мумкин.',createContact:'Бу одамни Б24да сизга контакт қилиб яратайликми?',contactHint:'Белгисиз рақамни фақат дорихонага сақлаймиз, одам исмисиз. Контакт бор бўлса, ўшани ишлатамиз.',name:'Контакт исми',nameHint:'Фамилия шарт эмас. Контакт бор бўлса, бўш қолдириш мумкин.',position:'Лавозим',reminder:'🔔 Сделкадаги эслатма',addReminder:'Клиент билан ишлаш учун сизга эслатма қўшайликми?',action:'Клиент билан нима қилиш керак?',actionHint:'Ўзингиз учун қисқа ёзинг — бот Telegramда эслатади.',deadline:'Қачон? Тошкент вақти',chooseDate:'📅 Сана ва вақтни танлаш',timezone:'🕒 Тошкент вақти',today:'Бугун',tomorrow:'Эртага',hour:'Вақт',apply:'Танлаш',support:'🛠 Техник ёрдам заявкаси',requestTitle:'Заявка мавзуси *',requestDescription:'Нима бўлди ва қандай ёрдам керак? *',recipientHint:'Навбатда қолдириш ёки техникка тайинлаш? Ботда йўналиш, ҳудуд ва техникни танлайсиз. Исм ва фамилия бўйича қидириш бор.',reviewHint:'Тугма қораламани ботга юборади. Б24да тасдиқлаганингиздан кейин сақлаймиз.',submit:'Ботда текшириш →',select:'Танланг',loadError:'Маълумотномалар очилмади. Формани ёпиб, қайта уриниб кўринг.',geoError:'Геопозиция олинмади. Рухсат беринг ёки ўтказиб юборинг.',openBot:'Формани Telegram-ботдаги тугмадан очинг. Оддий браузердан маълумот юборилмайди.',sizeError:'Матн жуда кўп. Тавсиф, номлар ёки манзилни қисқартиринг.',dateError:'Эслатма учун келажакдаги сана ва вақтни танланг.',sending:'⏳ Ботга юборяпмиз…'}
};
Object.assign(texts.ru,{discussion:'💬 Какие программы хотите обсудить с клиентом?',discussionHint:'Можно выбрать несколько программ.',discussionError:'Выберите хотя бы одну программу для обсуждения.',telegramReminderHint:'В выбранное время бот пришлёт вам напоминание в Telegram.',actionOther:'Напишите своё действие',actionOtherHint:'Коротко напишите своими словами, о чём вам напомнить.',call:'Позвонить',visit:'Приехать',check_in:'Уточнить, как идут дела',other:'Другое'});
Object.assign(texts.uz,{discussion:'💬 Мижоз билан қайси дастурларни муҳокама қилмоқчисиз?',discussionHint:'Бир нечта дастурни танлаш мумкин.',discussionError:'Муҳокама учун камида битта дастурни танланг.',telegramReminderHint:'Танланган вақтда бот сизга Telegramда эслатма юборади.',actionOther:'Ўз амалингизни ёзинг',actionOtherHint:'Нимани эслатиш кераклигини ўз сўзларингиз билан қисқа ёзинг.',call:'Қўнғироқ қилиш',visit:'Бориб кўриш',check_in:'Ишлар қандай кетаётганини сўраш',other:'Бошқа'});
Object.assign(texts.ru,{supportProgram:'💻 По какой программе нужна помощь?',supportProgramHint:'Можно выбрать программу, чтобы сузить список, или искать сразу по всем.',allPrograms:'Все программы',supportType:'🏷 Тип обращения (ТО) *',supportSearch:'🔎 Найти ошибку или проблему',supportSearchPlaceholder:'Например: чек, пароль, остатки',unknownTypeHint:'Если не знаете причину — выберите этот тип и опишите проблему ниже.',changeType:'Изменить тип',moreTypes:'Показать ещё',requestTitleHint:'Заполним по типу обращения. При желании уточните тему.',descriptionHint:'Опишите, что не работает и какая помощь нужна. Это описание сохранится в комментарии к заявке.',unknownDescriptionHint:'Опишите проблему своими словами: что произошло, в какой программе и какая помощь нужна.',supportTypeError:'Выберите тип обращения. Если не знаете причину — нажмите «Неопознанная ошибка: нужно уточнить».',noTypes:'Ничего не найдено. Попробуйте другое слово или выберите «Все программы». Можно выбрать неопознанную ошибку и описать проблему.',typeCount:'Найдено: {count}. Показано: {shown}.',catalogueLoading:'⏳ Загружаем типы обращения…'});
Object.assign(texts.uz,{supportProgram:'💻 Қайси дастур бўйича ёрдам керак?',supportProgramHint:'Рўйхатни қисқартириш учун дастурни танланг ёки барча дастурлар бўйича қидиринг.',allPrograms:'Барча дастурлар',supportType:'🏷 Мурожаат тури (ТО) *',supportSearch:'🔎 Хато ёки муаммони қидириш',supportSearchPlaceholder:'Масалан: чек, пароль, остатки',unknownTypeHint:'Сабабини билмасангиз — шу турни танлаб, муаммони қуйида ёзинг.',changeType:'Турни ўзгартириш',moreTypes:'Яна кўрсатиш',requestTitleHint:'Мурожаат тури бўйича тўлдирамиз. Истасангиз, мавзуни аниқлаштиринг.',descriptionHint:'Нима ишламаётганини ва қандай ёрдам кераклигини ёзинг. Тавсиф заявка изоҳига сақланади.',unknownDescriptionHint:'Муаммони ўз сўзларингиз билан ёзинг: нима бўлди, қайси дастурда ва қандай ёрдам керак?',supportTypeError:'Мурожаат турини танланг. Сабабини билмасангиз — «Неопознанная ошибка: нужно уточнить»ни босинг.',noTypes:'Топилмади. Бошқа сўз билан қидиринг ёки «Барча дастурлар»ни танланг. Номаълум хатони танлаб, муаммони ёзиш ҳам мумкин.',typeCount:'Топилди: {count}. Кўрсатилди: {shown}.',catalogueLoading:'⏳ Мурожаат турларини юклаяпмиз…'});
Object.assign(texts.ru,{supportContact:'👤 С кем связаться по заявке?',usePharmacyContacts:'Использовать контакты аптеки',addSupportContact:'Указать контактное лицо',pharmacyContactsHint:'Добавим к заявке контакты, которые уже привязаны к аптеке в Б24. Новый контакт создавать не будем.',supportContactName:'Имя контактного лица *',supportContactNameHint:'Фамилия необязательна.',supportContactPhone:'Телефон контактного лица *',supportContactPhoneHint:'Можно без +998. Если номер уже есть в Б24, используем существующий контакт. Иначе создадим новый на вас и привяжем к заявке и компании аптеки.'});
Object.assign(texts.uz,{supportContact:'👤 Заявка бўйича ким билан боғланиш керак?',usePharmacyContacts:'Дорихона контактларидан фойдаланиш',addSupportContact:'Боғланиш учун одамни кўрсатиш',pharmacyContactsHint:'Б24да дорихонага боғланган контактларни заявкага қўшамиз. Янги контакт яратмаймиз.',supportContactName:'Боғланиш учун одамнинг исми *',supportContactNameHint:'Фамилия мажбурий эмас.',supportContactPhone:'Боғланиш учун одамнинг телефони *',supportContactPhoneHint:'+998сиз мумкин. Рақам Б24да бўлса, мавжуд контактдан фойдаланамиз. Бўлмаса, сизга янги контакт яратиб, заявка ва дорихона компаниясига боғлаймиз.'});
const el=id=>document.getElementById(id), field=name=>form.elements[name];
let typeLimit=12, autoRequestTitle='';
Object.assign(texts.ru,{supportProgramNeeded:'Для этого типа обращения выберите программу, по которой нужна помощь.',supportFallback:'Точного типа в Б24 нет: сохраним выбранный тип в описании, а в поле Б24 отметим «Неопознанная ошибка: нужно уточнить».'});
Object.assign(texts.uz,{supportProgramNeeded:'Бу мурожаат тури учун ёрдам керак бўлган дастурни танланг.',supportFallback:'Б24да аниқ мос тур йўқ: танланган турни тавсифга сақлаймиз, Б24 майдонида «Неопознанная ошибка: нужно уточнить»ни белгилаймиз.'});
function mappingHint(row){if(!row||row.id===reference?.support?.unknown_id)return '';const product=field('support_program').value;if(row.requires_program&&!product)return texts[lang].supportProgramNeeded;const matches=(row.native_matches||[]).filter(item=>!item.program_ids.length||item.program_ids.includes(product));return matches.length===1?'':texts[lang].supportFallback;}
function searchText(value){return value.normalize('NFKC').toLocaleLowerCase().replace(/ё/g,'е').replace(/[\[\]_-]/g,' ');}
function availableType(row){const product=field('support_program').value;return !product||!(row.program_ids||[]).length||row.program_ids.includes(product);}
function supportOptions(){
  const catalog=reference?.support, selected=catalog?.types.find(row=>row.id===field('support_type').value);
  const product=field('support_program').value;field('support_program').replaceChildren(new Option(texts[lang].allPrograms,''));
  for(const row of catalog?.programs||[])field('support_program').add(new Option(row.title,row.id));field('support_program').value=product;
  el('supportSearch').placeholder=texts[lang].supportSearchPlaceholder;
  el('unknownType').hidden=!catalog?.unknown_id;el('unknownTypeHint').hidden=!catalog?.unknown_id;
  if(catalog?.unknown_id)el('unknownType').textContent=catalog.types.find(row=>row.id===catalog.unknown_id).title;
  el('selectedType').hidden=!selected;el('typeSearchPanel').hidden=Boolean(selected);
  el('selectedTypeTitle').textContent=selected?'✅ '+selected.title:'';
  el('supportMappingHint').textContent=mappingHint(selected);el('supportMappingHint').hidden=!el('supportMappingHint').textContent;
  el('requestDescriptionHint').textContent=selected?.id===catalog?.unknown_id?texts[lang].unknownDescriptionHint:texts[lang].descriptionHint;
  supportResults();
}
function supportResults(){
  const catalog=reference?.support, words=searchText(el('supportSearch').value).split(/\s+/).filter(Boolean);
  const rows=(catalog?.types||[]).filter(row=>row.id!==catalog.unknown_id&&availableType(row)&&words.every(word=>searchText([row.title,...(row.aliases||[])].join(' ')).includes(word)));
  el('supportTypeResults').replaceChildren();
  for(const row of rows.slice(0,typeLimit)){const button=document.createElement('button');button.type='button';button.className='typeOption';button.dataset.typeId=row.id;button.textContent=row.title;button.disabled=mode!=='support';button.addEventListener('click',()=>chooseType(row.id));el('supportTypeResults').append(button);}
  el('typeCount').textContent=!catalog?texts[lang].catalogueLoading:rows.length?texts[lang].typeCount.replace('{count}',rows.length).replace('{shown}',Math.min(rows.length,typeLimit)):texts[lang].noTypes;
  el('moreTypes').hidden=rows.length<=typeLimit;
}
function chooseType(id){
  const row=reference?.support?.types.find(row=>row.id===id);if(!row)return;
  field('support_type').value=id;
  if(!field('request_title').value||field('request_title').value===autoRequestTitle){autoRequestTitle=row.title.replace(/^\[[^\]]+\]\s*/,'').slice(0,100);field('request_title').value=autoRequestTitle;}
  supportOptions();error('');field('request_description').focus();
}
function discussionOptions(){const selected=new Set([...document.querySelectorAll('[name=discussion_programs]:checked')].map(node=>node.value));el('discussionChoices').replaceChildren();for(const row of reference?.discussion_programs||[]){const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.name='discussion_programs';input.value=String(row.id);input.checked=selected.has(input.value);input.addEventListener('change',()=>error(''));input.disabled=mode!=='deal';const span=document.createElement('span');span.textContent=row.title.replace(/^◉\s*/,'');label.append(input,span);el('discussionChoices').append(label);}}
function reminderOptions(){const value=field('reminder_action').value;options('reminder_action',['call','visit','check_in','other'].map(id=>({id,title:texts[lang][id]})));field('reminder_action').value=value;}

function error(message){el('error').textContent=message;el('error').hidden=!message;if(message)el('error').scrollIntoView({block:'nearest'});}
function options(name,rows){const select=field(name),value=select.value;select.replaceChildren(new Option(texts[lang].select,''));for(const row of rows||[])select.add(new Option(row.title,String(row.id)));if((rows||[]).some(row=>String(row.id)===value))select.value=value;}
function sync(){
  const isNew=field('pharmacy_kind').value==='new',isExisting=field('pharmacy_kind').value==='existing',isSupport=mode==='support';
  el('pharmacyData').hidden=!isNew;el('existingPharmacy').hidden=!isExisting;
  field('fom_id').disabled=!isExisting;field('fom_id').required=isExisting;
  for(const node of el('pharmacyData').querySelectorAll('input,select')){node.disabled=!isNew;node.required=isNew&&node.hasAttribute('data-required');}
  el('pharmacyContactConsent').hidden=isSupport;field('create_contact').disabled=!isNew||isSupport;
  const contact=isNew&&!isSupport&&field('create_contact').checked;
  el('newContact').hidden=!contact;field('contact_name').disabled=!contact;field('position').disabled=!contact;field('phone').required=contact;
  el('supportContact').hidden=!isSupport;
  for(const node of document.querySelectorAll('[name=support_contact]'))node.disabled=!isSupport;
  const supportPerson=isSupport&&field('support_contact').value==='person';
  el('supportContactFields').hidden=!supportPerson;el('pharmacyContactsHint').hidden=supportPerson;
  for(const name of ['support_contact_name','support_contact_phone']){field(name).disabled=!supportPerson;field(name).required=supportPerson;}
  el('support').hidden=!isSupport;
  for(const name of ['request_title','request_description','support_type','support_program']){field(name).disabled=!isSupport;field(name).required=isSupport&&['request_title','request_description'].includes(name);}
  el('supportSearch').disabled=!isSupport||!reference?.support;el('unknownType').disabled=!isSupport||!reference?.support;
  el('reminder').hidden=mode!=='deal';const reminder=mode==='deal'&&field('reminder').checked;
  el('reminderFields').hidden=!reminder;el('discussion').hidden=mode!=='deal';
  field('reminder_action').disabled=!reminder;field('reminder_action').required=reminder;
  const other=reminder&&field('reminder_action').value==='other';el('customAction').hidden=!other;
  field('next_step').disabled=!reminder;field('next_step').required=other;
  if(reminder&&field('reminder_action').value&&field('reminder_action').value!=='other')field('next_step').value=texts[lang][field('reminder_action').value];
  field('deadline').disabled=!reminder;
}
function tashNow(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tashkent',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
let pickedDay=tashNow().slice(0,10),month=pickedDay.slice(0,7);
function dateLabel(value){return new Intl.DateTimeFormat(lang==='uz'?'uz-Cyrl-UZ':'ru-RU',{timeZone:'Asia/Tashkent',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value+'+05:00'));}
function calendar(){const first=new Date(month+'-01T00:00:00Z'),year=first.getUTCFullYear(),m=first.getUTCMonth();el('monthLabel').textContent=new Intl.DateTimeFormat(lang==='uz'?'uz-Cyrl-UZ':'ru-RU',{month:'long',year:'numeric',timeZone:'UTC'}).format(first);el('previousMonth').disabled=month<=tashNow().slice(0,7);el('weekdays').replaceChildren();for(const title of (lang==='uz'?['Ду','Се','Чо','Па','Жу','Ша','Як']:['Пн','Вт','Ср','Чт','Пт','Сб','Вс'])){const span=document.createElement('span');span.textContent=title;el('weekdays').append(span);}el('days').replaceChildren();for(let n=0;n<(first.getUTCDay()+6)%7;n++)el('days').append(document.createElement('span'));for(let day=1;day<=new Date(Date.UTC(year,m+1,0)).getUTCDate();day++){const value=month+'-'+String(day).padStart(2,'0'),button=document.createElement('button');button.type='button';button.textContent=day;button.dataset.date=value;button.disabled=value<tashNow().slice(0,10);button.setAttribute('aria-pressed',String(value===pickedDay));button.addEventListener('click',()=>{pickedDay=value;calendar();});el('days').append(button);}el('selectedDate').textContent=dateLabel(pickedDay+'T'+el('hour').value);}
function render(){document.documentElement.lang=lang;for(const node of document.querySelectorAll('[data-i18n]'))node.textContent=texts[lang][node.dataset.i18n];el('language').textContent=lang==='ru'?'🇺🇿 Ўзбекча':'🇷🇺 Русский';if(reference){options('business_region',reference.regions);options('city',reference.cities[field('business_region').value]||[]);options('program',reference.programs);options('position',reference.positions);discussionOptions();}supportOptions();reminderOptions();if(field('deadline').value)el('chooseDeadline').textContent='📅 '+dateLabel(field('deadline').value);calendar();sync();tg?.MainButton?.setText(texts[lang].submit);}
for(let h=0;h<24;h++)for(const minute of ['00','30']){const value=String(h).padStart(2,'0')+':'+minute;el('hour').add(new Option(value,value));}el('hour').value='18:00';
el('language').addEventListener('click',()=>{lang=lang==='ru'?'uz':'ru';render();});for(const radio of document.querySelectorAll('[name=pharmacy_kind]'))radio.addEventListener('change',sync);field('business_region').addEventListener('change',()=>options('city',reference?.cities[field('business_region').value]||[]));field('create_contact').addEventListener('change',sync);for(const radio of document.querySelectorAll('[name=support_contact]'))radio.addEventListener('change',sync);field('reminder').addEventListener('change',sync);field('reminder_action').addEventListener('change',()=>{if(field('reminder_action').value==='other')field('next_step').value='';sync();});
el('chooseDeadline').addEventListener('click',()=>{calendar();el('datePicker').showModal();});el('closeDate').addEventListener('click',()=>el('datePicker').close());el('hour').addEventListener('change',calendar);for(const button of document.querySelectorAll('[data-day-offset]'))button.addEventListener('click',()=>{const d=new Date(tashNow().slice(0,10)+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+Number(button.dataset.dayOffset));pickedDay=d.toISOString().slice(0,10);month=pickedDay.slice(0,7);calendar();});for(const [id,shift] of [['previousMonth',-1],['nextMonth',1]])el(id).addEventListener('click',()=>{const d=new Date(month+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+shift);month=d.toISOString().slice(0,7);calendar();});el('applyDate').addEventListener('click',()=>{const value=pickedDay+'T'+el('hour').value;if(value<=tashNow()){el('selectedDate').textContent=texts[lang].dateError;return;}field('deadline').value=value;el('chooseDeadline').textContent='📅 '+dateLabel(value);el('datePicker').close();error('');});
el('location').addEventListener('click',()=>{error('');if(!navigator.geolocation){error(texts[lang].geoError);return;}el('location').disabled=true;navigator.geolocation.getCurrentPosition(position=>{point={latitude:position.coords.latitude,longitude:position.coords.longitude};document.querySelector('#coordinates span').textContent=point.latitude.toFixed(6)+', '+point.longitude.toFixed(6);el('coordinates').hidden=false;el('location').disabled=false;},()=>{error(texts[lang].geoError);el('location').disabled=false;},{enableHighAccuracy:true,timeout:15000,maximumAge:0});});el('removeLocation').addEventListener('click',()=>{point=undefined;el('coordinates').hidden=true;});
function submit(){if(sending)return;error('');if(mode==='support'&&!field('support_type').value){error(reference?.support?texts[lang].supportTypeError:texts[lang].catalogueLoading);el('supportTypeLabel').scrollIntoView({block:'center'});el('unknownType').focus();return;}const type=reference?.support?.types.find(row=>row.id===field('support_type').value);if(mode==='support'&&type?.requires_program&&!field('support_program').value){error(texts[lang].supportProgramNeeded);field('support_program').focus();return;}if(!form.reportValidity())return;if(mode==='deal'&&!document.querySelector('[name=discussion_programs]:checked')){error(texts[lang].discussionError);el('discussion').scrollIntoView({block:'center'});return;}if(mode==='deal'&&field('reminder').checked&&(!field('deadline').value||field('deadline').value<=tashNow())){error(texts[lang].dateError);el('chooseDeadline').focus();return;}if(!tg?.sendData||!query.get('token')||tg.platform==='unknown'){error(texts[lang].openBot);return;}const isNew=field('pharmacy_kind').value==='new';const data={token:query.get('token'),mode,pharmacy_kind:field('pharmacy_kind').value,contact_policy:'optional',create_contact:isNew&&mode!=='support'&&field('create_contact').checked,support_contact:mode==='support'?field('support_contact').value:'pharmacy',reminder:mode==='deal'&&field('reminder').checked,discussion_programs:mode==='deal'?[...document.querySelectorAll('[name=discussion_programs]:checked')].map(node=>node.value):[]};for(const key of ['fom_id','inn','company_name','title','phone','contact_name','position','business_region','city','address','program','reminder_action','next_step','deadline','request_title','request_description','support_type','support_program','support_contact_name','support_contact_phone'])data[key]=field(key).disabled?'':field(key).value.trim();if(isNew&&point)data.location=point;const payload=JSON.stringify(data);if(new TextEncoder().encode(payload).length>4096){error(texts[lang].sizeError);return;}sending=true;const button=form.querySelector('[type=submit]');button.disabled=true;button.textContent=texts[lang].sending;tg.MainButton?.showProgress();try{tg.sendData(payload);}catch(e){sending=false;button.disabled=false;button.textContent=texts[lang].submit;tg.MainButton?.hideProgress();error(texts[lang].openBot);}}
el('supportSearch').addEventListener('input',()=>{typeLimit=12;supportResults();});el('supportSearch').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();const button=el('supportTypeResults').querySelector('button');if(button&&el('supportTypeResults').children.length===1)button.click();else button?.focus();}});
field('support_program').addEventListener('change',()=>{typeLimit=12;const row=reference?.support?.types.find(row=>row.id===field('support_type').value);if(row&&!availableType(row))field('support_type').value='';supportOptions();error('');});
el('unknownType').addEventListener('click',()=>chooseType(reference?.support?.unknown_id));el('moreTypes').addEventListener('click',()=>{typeLimit+=20;supportResults();});el('changeType').addEventListener('click',()=>{field('support_type').value='';supportOptions();el('supportSearch').focus();});
form.addEventListener('submit',event=>{event.preventDefault();submit();});if(mode==='pharmacy'){field('pharmacy_kind').value='new';el('pharmacyChoice').hidden=true;}render();tg?.ready();tg?.expand();tg?.MainButton?.onClick(submit);tg?.MainButton?.show();fetch('reference.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('reference');return response.json();}).then(data=>{reference=data;render();}).catch(()=>error(texts[lang].loadError));
